### ISSUE TITLE
CIで検査をできるようにする( Check with CI )

### ISSUE THREAD

**Issue by takanakahiko** [jagsc/blog#4]
# 概要(Overview)

レビュー工程にCIに夜検査を追加する
(Add CI check to the review flow.)

# 詳細(Details)

- プルリクエスト発行時にCIrcleCIでjekyllのビルドを行う
(Build in CircleCI when create pull Request.)

- masterブランチのプロテクトにCircleCIの通過を追加する
(Add CircleCI check to setting of master branch protection )

**Comment by prprhyt** [comment]
参考: https://jekyllrb.com/docs/continuous-integration/circleci/#1-follow-your-project-on-circleci

**Comment by prprhyt** [comment]
Done at #18
